spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/devlinks
spring.datasource.username=dev
spring.datasource.password=dev

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
