spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/devlinks
spring.datasource.username=dev
spring.datasource.password=dev

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#Security
logging.level.org.springframework.security=DEBUG
logging.level.com.example.demo.security=DEBUG

# JWT Configuration
app.jwt.secret=I0RvEYyXRiq6+9wM4yeAhVe6ugtbkf+t1nc2QFyDWJ5ezs9vS+LjmU/E4ZSmXYcUDlonMXk9RQ0j8OpxVBAfXQ==
app.jwt.expiration-ms=3600000